### ISSUE TITLE
GPU OOM error

### ISSUE THREAD

**Issue by TiagoMSSantos** [TiagoMSSantos/MobileRT#283]
There seems to be a GPU memory leak on the custom GLSurfaceView.Renderer.
```
10-20 22:52:51.729 12565 15511 D EGL_emulation: eglMakeCurrent: 0xedc17400: ver 3 1 (tinfo 0xedc36d30)
10-20 22:52:51.735 17165 17165 I MainActivity: initializePickerResolutions
10-20 22:52:51.735 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: resetErrno start
10-20 22:52:51.735 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: resetErrno finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize start
10-20 22:52:51.736 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: rtResize finish
10-20 22:52:51.737  1746  3631 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 9052160
10-20 22:52:51.739  1746  1788 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
10-20 22:52:51.739  1746  1788 E gralloc_ranchu: gralloc_alloc failed to create ashmem region: Too many open files
10-20 22:52:51.739 10926 11120 E GraphicBufferAllocator: Failed to allocate (1080 x 1920) layerCount 1 format 1 usage 933: 5
10-20 22:52:51.739 10926 11120 E BufferQueueProducer: [puscas.mobilertapp/puscas.mobilertapp.MainActivity#0] dequeueBuffer: createGraphicBuffer failed
10-20 22:52:51.739 17165 17165 E Surface : dequeueBuffer failed (Out of memory)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: OutOfResourcesException initializing HW surface
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: android.view.Surface$OutOfResourcesException
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Surface.nativeLockCanvas(Native Method)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Surface.lockCanvas(Surface.java:371)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3677)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3638)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.os.Handler.handleCallback(Handler.java:883)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.os.Looper.loop(Looper.java:214)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-20 22:52:51.741 11061 11457 I WindowManager: Out of memory for surface!  Looking for leaks...
10-20 22:52:51.741 11061 11457 W WindowManager: LEAKED SURFACE (app token hidden): Window{d750d48 u0 com.android.launcher3/com.android.launcher3.Launcher} surface=Surface(name=com.android.launcher3/com.android.launcher3.Launcher)/@0xa8c1ebb token=AppWindowToken{c7f10c4 token=Token{4a12fd7 ActivityRecord{b58e356 u0 com.android.launcher3/.Launcher t2}}}
10-20 22:52:51.741 11061 11457 W WindowManager: Looks like we have reclaimed some memory, clearing surface for retry.
10-20 22:52:51.758 17165 17165 I MainActivity: initializePickerResolutions
10-20 22:52:51.759 17165 17165 D LOG     : Utils.cpp:239: checkSystemError: resetErrno start
```

```
10-20 22:52:51.739  1746  1788 E gralloc_ranchu: gralloc_alloc failed to create ashmem region: Too many open files
10-20 22:52:51.739 10926 11120 E GraphicBufferAllocator: Failed to allocate (1080 x 1920) layerCount 1 format 1 usage 933: 5
10-20 22:52:51.739 10926 11120 E BufferQueueProducer: [puscas.mobilertapp/puscas.mobilertapp.MainActivity#0] dequeueBuffer: createGraphicBuffer failed
10-20 22:52:51.739 17165 17165 E Surface : dequeueBuffer failed (Out of memory)
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: OutOfResourcesException initializing HW surface
10-20 22:52:51.740 17165 17165 E ViewRootImpl[MainActivity]: android.view.Surface$OutOfResourcesException
```
Further investigation is necessary.

To recreate this just execute:
```
source scripts/helper_functions.sh
callCommandUntilError bash scripts/run_tests_android.sh -t release & fg;
```
And wait a while. Eventually the Android emulator will not be able to pass the Load Shaders test: `MainRendererTest#testLoadFragmentShader`.

OpenGL programs and shaders are being created at each frame, but they don't seem to be destroyed.

**Comment by TiagoMSSantos** [comment]
Temporary solution is in the commit: c6d2ef3b4d841bceff734d4232146b02520a99cd
